#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Ren Zhang @ ryanzjlib dot gmail dot com
import os
import json
SETTINGS = json.load(open('../SETTINGS.json'))
IMAGE_SIZE = tuple(SETTINGS['IMAGE_SIZE'])
NUM_CLASSES = SETTINGS['NUM_CLASSES']
DATA_DIR = SETTINGS['DATA_DIR']
LOG_DIR = SETTINGS['LOG_DIR']
MODEL_DIR = SETTINGS['MODEL_DIR']
SUB_DIR = SETTINGS['SUB_DIR']
OUT_DIR = SETTINGS['OUT_DIR']
TRAIN_IMAGE_DIRNAME = SETTINGS['TRAIN_IMAGE_DIRNAME']
TEST_IMAGE_DIRNAME = SETTINGS['TEST_IMAGE_DIRNAME']
TRAIN_IMAGE_DIR = os.path.join(DATA_DIR, TRAIN_IMAGE_DIRNAME)
TEST_IMAGE_DIR = os.path.join(DATA_DIR, TEST_IMAGE_DIRNAME)
